### PR TITLE
Add Lacros icon

### PR DESCRIPTION
**Pull request by tomayac**
Add missing Lacros icon for [App Menu API](https://fugu-tracker.web.app/#:~:text=Fugu%20Request%3A%20App%20Menu%20API%20for%20installed%20PWAs).

### CODE REVIEW

**Review by beaufortfrancois — DISMISSED** [review]
Can you run it through https://jakearchibald.github.io/svgomg/?
I quickly got `937 bytes → 590 bytes 62.97%` but you may get more.

**Comment by tomayac** [comment]
Shrunk…

**Comment by beaufortfrancois** [comment]
LGTM

**Comment by beaufortfrancois** [comment]
@Snugug Can you merge?

**Pull request merged**
